apiVersion: v1
kind: Secret
metadata:
  name: n8n-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:yuNmrY3HLZ8=,iv:gddiCBg7sXwmDU0vSP8mYOowesThxp6yq3QFQUfI39w=,tag:b/0uZ2tv7DGxqZb6tmzuPw==,type:str]
  password: ENC[AES256_GCM,data:ybXKeXpwKiPtlQyQWciqRT6fURu8h9BELdmiiOMs0pdHwlCDR6Sh9eEb5w==,iv:rpI5McloIH4d/u4JBoEclE7umMUJXQ30kvmRXATez8A=,tag:QbfWqhAug+9z9Pyr0CvuYQ==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa0xNS3pkd213am4wREpn
        NFdaQmNybnNJSWRPenl5VWExeXIxS1BlTEZnClBJTmk1KzZzNlAvN0Y5eHp1S2hO
        RGd1RUhOTGU1N1Vab0p1bVNEZ2hMcmMKLS0tIG5zVkk2cWpoRU9IbDJUbWExajR6
        Tm1WdzdJb2hQK21MU2xSL2pTSGdSTDAKVwtcY3rgXPLg3x+qNu6eseAVR9t2aS/e
        3QfN0iHYK9TgRJa5eK58OvP5WH872hoLenyZg5l7bQKtGG6kPsRp1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:31:43Z"
  mac: ENC[AES256_GCM,data:zjqkuoWrCLmFxVRtiedwt4zznBrcy50miwx77BPb0w0jQNIKvp4k7hmVlGDBTp5uCvG9fD/o7gC7zPN2+tjGqMONrKAJt1+3RYBggL+2OYgPNZmUqFwV2BRDHxZXBHg9g5Xdhcys1zcIXwhH6AI60HZz5IJGgQ8yb4jjhev5tDM=,iv:OEs63m1YOKXrrG4NRlxhrjLljDik+WTlBQl3AsNiIU8=,tag:n6LXcnr7JwwgyAdn/hpAlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-pg-app
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:SNm/,iv:6WoeVWe5NpzaM8WQOvJJQ+PemJGNZvyPeqFbC7Sq04s=,tag:lMhjZycG+iVcSA72CgPrBA==,type:str]
  password: ENC[AES256_GCM,data:z1fNj9VRGvYGuegVOmWarJaTLQkdMzoLoRVZGw0GvxGD5q+Wj13+CQ/rdQ==,iv:nITVilvSEiOUGi2vgsALKjmzkQaVUqArFHDfHMhkurA=,tag:u9DslJZryxS8CLlzbaHnCw==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa0xNS3pkd213am4wREpn
        NFdaQmNybnNJSWRPenl5VWExeXIxS1BlTEZnClBJTmk1KzZzNlAvN0Y5eHp1S2hO
        RGd1RUhOTGU1N1Vab0p1bVNEZ2hMcmMKLS0tIG5zVkk2cWpoRU9IbDJUbWExajR6
        Tm1WdzdJb2hQK21MU2xSL2pTSGdSTDAKVwtcY3rgXPLg3x+qNu6eseAVR9t2aS/e
        3QfN0iHYK9TgRJa5eK58OvP5WH872hoLenyZg5l7bQKtGG6kPsRp1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:31:43Z"
  mac: ENC[AES256_GCM,data:zjqkuoWrCLmFxVRtiedwt4zznBrcy50miwx77BPb0w0jQNIKvp4k7hmVlGDBTp5uCvG9fD/o7gC7zPN2+tjGqMONrKAJt1+3RYBggL+2OYgPNZmUqFwV2BRDHxZXBHg9g5Xdhcys1zcIXwhH6AI60HZz5IJGgQ8yb4jjhev5tDM=,iv:OEs63m1YOKXrrG4NRlxhrjLljDik+WTlBQl3AsNiIU8=,tag:n6LXcnr7JwwgyAdn/hpAlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
