apiVersion: v1
kind: Secret
metadata:
  name: sing-box-age-key
stringData:
  age.key: ENC[AES256_GCM,data:0dq0yqaEQmjLpAvMqztpvknwuLxsUcXDVZ2cPAzbWBQTdbz3gn/9a0IxTRGhM9PoJVDWig9ylTcHiFWitz3glM6Qw0xAkisWDM8=,iv:B01U4AHGIGJ6LdH5TDVVZIYFhHqPpYLEJbGWAV6WhF4=,tag:UPvXPiFWcSbsJ8kpEgEKTQ==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmR0E2ckNNNEhiZUE5VTdv
        Wmp5QzVtNXdXbWhCVjk1WEovQjBLNmlHeWhRClJNcm1FRCt2WUJNR25TN0k2QXcx
        TGZoU2FqdTdBeFp1QmQ3eUNjWG1GZ3cKLS0tIEVmN2lnMHplYzVZQi9jZmhBMUpy
        SnRyTmZuUjVCMFJneHFLVE16ZUtnbDQK4lXo6patftJOTgySShwhhOQNfn9/4XQW
        f0XiwWme/BL7J4Lrvp4Iqs11Du/d8hstN4Rit0Ak8sjRaNCJW9EUlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T07:11:13Z"
  mac: ENC[AES256_GCM,data:tQ9uZ/vWKKwsWUdAlcLdNikpR3sr4f7nA9l86pVdV9IRUgDdhU4TarnF6GSRapaSPdI72dmiUiqCCXNG5Fcvxottq2YDsLsneiKVeFwMpp4vapa7HtqNlhs8kiHdQcsgHiRMI5vQXf/VBbVup95BwuZhXNS2d3RQdxyx1VhUeVo=,iv:kRj8/z5HDoSHVEg9fM/aCWlnd0yWdT5OffDanUFq1ls=,tag:F1Ox3yVkoAZMMlC7LizAdg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
