apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: forgejo-pull-secret
data:
  .dockerconfigjson: ENC[AES256_GCM,data:37wHIrPBZlPktg/Fyef2cKUFpWZlWX23mOMiXL7dIYn/9CIcP5+AaDpz8oCtVSzE+tGzGhQeJjfZUCVXG8JXVakdRXbCypak+4RPA2ZaNZK2dZjKRfhGAeJetdvnyCGSviYkqmRRkblbfWbeM5sK9YCbFx+rAOAJHA4nF/dkG5uiS3yQoL/K6PN51RcwPSeFIDO7GT1RBnWkH4KND/BMpTx5cNgeeEcruIlfcz48bU2RYqPaWnzOCkJvBCY=,iv:qXY+hWrNneHfr3S50oT6zbOziwGri7kLmztsUcKsER0=,tag:j/qXsriPzAT/DlrECC79sQ==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpajNLeHFmckVDSVdnSzFC
        Q25HaW91SVJGaG1JOTU2d1hUMkJyZlo2WjAwClplR3dOK1VjUWwvL3A3WVFkWVFV
        Ui9EVW9DSTBhc3QwMTI0V3BOU1pRTnMKLS0tIGJsU2dmZThoZ1ptQnFVek95VXJi
        d2wxWHdiaEFBZmliMWdMTHppL3BNd1EKsTN8ttX6VhYu9lnlIbcxZ0Bs7nlo/ysx
        qj3nXeU4niHl8zoOcOxGiHXrIGf/Fyj71DHozRhvW+BMgjqcNiy/xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T04:45:27Z"
  mac: ENC[AES256_GCM,data:qQhE1zlYpitdI+K35DfrYXDxt47M0CD/Du9iEG8xFK16iuMS+auq1MHWZMBKUjOrWy4uOTxgn+BzsoMob6iRdIvHpwcakA5yrCM3SOIM6VwqpG7rF1Pcik2SB6Kf6zzXsPQwctgtFGym1sT+VCKs+uQHjvEbooS+5y7rsXNoEFM=,iv:TpcAFnN6YV02lWWgNm/Q97RfCQnc1vQp1PZ+AGkmoC8=,tag:7TTcUAXZrxAS/cdYHqkcYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
