apiVersion: v1
kind: Secret
metadata:
  name: coder-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:YmOYlK/HAwI=,iv:zdEYhlQ3B72Tyoktj4Kd1H4hOfZWM2/sGTpZNKcMzSE=,tag:VYC+jSb+mtz3qh8P+XvaKg==,type:str]
  password: ENC[AES256_GCM,data:R44jGZAaQ/7aVj7ohw/UfM9dHh9msAUaJb5yt9Bhc8EUocj+NhVkCayJyA==,iv:sYo0GYlzYswS9ZjoD2Qfsgh0f9Xd/xjWrgz76x8B/PY=,tag:vIBnZoyMB7X969jbxtxNYA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMW81Qkd1ZEQ4Y3dYOFcv
        Z3M0UEFqRnVMSWFsbjRJYUVIVUc2V2w4MWhrCktJYlhkclhyT0tQZkhXdnl6TW9Q
        RERlbkhSN1Q1MDVHU1lIR1JEUDJJb1kKLS0tIHhWVDFaekRjKytadTExWmFwNkNY
        QmdHN1NPZWJiS2VBRVZCZ2UzRWZtMW8KiVVv64sYnJkgTl5Dr262op6+dpH2Pyq8
        7FLDMdIdqnZjsTcC/9iAvAOoOUbJQB0a2BARfGE08gKo4mVS0fYAQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:31:43Z"
  mac: ENC[AES256_GCM,data:eMb4b2TLx/5LeOGIt3qaLP8vOABVkTSx6RO144kWClqSvBqTl9UzUg1gi+rPb1C15/ryvIcEpbBUAIgU4PVMuJoRIpBIarY0eNYPHfBrYigJtecmuJLY4Rn4BX5peGFCTCTmAqdbKlfiShOZST8IztgOBf+b0L5blPacs+YAUtA=,iv:03D6lrZx6aksNHeOOtfIo2ga/NTUh/N8xQQEIk5R518=,tag:tautpjpNHZEd6dtnTkP8Pw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: coder-pg-app
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:z9Pk0iM=,iv:pwbuFwL/z303bq8D3VkNxwUxhww/7Lu8KZ948p1WQGI=,tag:/NcEV7R9nBEoys3j52jkxA==,type:str]
  password: ENC[AES256_GCM,data:eTsxaN+QEfV04Jz5TjLmRzt/grivWxNtvgbcxxom/Wav7QI70lI2unaGlw==,iv:KedOJCCh1/bprZjdHeEj+qdBEmHtY22Ucb1OGJY5cQk=,tag:7cvui74odFLPQBF0M5pspA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMW81Qkd1ZEQ4Y3dYOFcv
        Z3M0UEFqRnVMSWFsbjRJYUVIVUc2V2w4MWhrCktJYlhkclhyT0tQZkhXdnl6TW9Q
        RERlbkhSN1Q1MDVHU1lIR1JEUDJJb1kKLS0tIHhWVDFaekRjKytadTExWmFwNkNY
        QmdHN1NPZWJiS2VBRVZCZ2UzRWZtMW8KiVVv64sYnJkgTl5Dr262op6+dpH2Pyq8
        7FLDMdIdqnZjsTcC/9iAvAOoOUbJQB0a2BARfGE08gKo4mVS0fYAQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:31:43Z"
  mac: ENC[AES256_GCM,data:eMb4b2TLx/5LeOGIt3qaLP8vOABVkTSx6RO144kWClqSvBqTl9UzUg1gi+rPb1C15/ryvIcEpbBUAIgU4PVMuJoRIpBIarY0eNYPHfBrYigJtecmuJLY4Rn4BX5peGFCTCTmAqdbKlfiShOZST8IztgOBf+b0L5blPacs+YAUtA=,iv:03D6lrZx6aksNHeOOtfIo2ga/NTUh/N8xQQEIk5R518=,tag:tautpjpNHZEd6dtnTkP8Pw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
