# Coder application secrets. pg-connection-url is constructed from
# the CNPG app credentials (carried over freshly — internal to this
# cluster, no need to match swarm-01). OIDC values match the row in
# authentik's restored DB (`Coder @ Beacoworks`, slug=coder), and
# the swarm-01 secret manifest's values matched authentik already
# so we carry both verbatim.
apiVersion: v1
kind: Secret
metadata:
  name: coder-secret
stringData:
  pg-connection-url: ENC[AES256_GCM,data:uJxiwbx4lkDnWFZ8wBI5a5xft/PkPVWJj6Q9FfX/fEx010LZk70sPBnUGbMuQfrO5X6Te1htN2wGsbYFY3WDDP/TrOzXCSQvH4i76mbmtjMhDHXQIiziTLS6dcLbMA==,iv:6y9taDmgnzrW9i0bbeTaYwVAbFjBQTHEE5AhOdeUtU8=,tag:EujHCq6zhPGaRuIjyxe3bA==,type:str]
  oidc-client-id: ENC[AES256_GCM,data:Xlkp7gl6yyc3joFoBYCi2hRYbV8u7Wry+gcKraAIj4tWAVg/jDOWnw==,iv:ybeOmXoBvERILxrntO1M5wzqnksSyPMcmtAm4r0GojI=,tag:Kvs0CEMAAPx+0U6ejCnmrQ==,type:str]
  oidc-client-secret: ENC[AES256_GCM,data:UyauJgNLw8HmeQEN3zFKSZlgdIN9iYXwVJllhCVp6N0gBoEI0nYMYX7OWPu4TNI0Bl9DGj7KfF6twN923GJ/n94WLtqvDUMwVIAHkoyfW2cKUaqre6UsqNgvy3DTqGoVREAR5bbJyYomZjPqb3J8IWuGC710m4BB2WiEDL3VcmE=,iv:Q+XbYsrDTckjPc0k7jnhCbmKVP6DybET05CltOPP7Vw=,tag:mCcjVQXuS5Mx6INAxmojJQ==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT3RnNEpUeS90ZGpGdVMv
        NThpRkRjM29Hc1lpTXdJejhRdEdZRXdxc0RRCkM3N2NLMWZJblZuNDYvZjhucWNQ
        S1ArTVdTaGtydXF6Q2ZMSUYvai9FZ00KLS0tIFgwVlU4Q3ltSmQvZDhrcXVja3JN
        Yk80NG9PcTlXQThseEdPcDlzM1ZrcTAKOUFzuVLWeW04jZ/cUY3eXV0bY6jJ9m+n
        Ad8h6XSNmJr5Ikfy+ICL0Lyz4FvJyYN+CN4XFZlWVVaFmq74l+MFzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:31:43Z"
  mac: ENC[AES256_GCM,data:5PBpT3BPbVS2STWTHOVqAahCCDlUKU8496h8MaVTZsFGcQpWySYXJYwfa077TnCg7+chLs/I0z42y4p3xhXa/8vX6DUzlCeFflWc24No9EJWHDFAG8VPIOiSNZEn5xPvtge2SLrm9LaWtum/Qc4+PvPMKy3Eu5BYf+KS7DKYimc=,iv:+yToWJtQBeafNL03VkViuYtbQz8njMI/xmzmO/899AI=,tag:+FRNLrYj/FEgqBA/RwifJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
