apiVersion: v1
kind: Secret
metadata:
  name: coder-workspace-agent
  namespace: development
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:wIoJ7mbqQ6FW5nHnq3MHJfgjaqP5haQ9Vz+eDzfC24Q18zFGOS5qOtnPUCw7ehf7jeXF1ii8N8G/kHl8rQ==,iv:PsBKGo15S7jXnZZ02kBeusKT8SfabkUsTZ7mvYJi/kM=,tag:s9ebKhWFkPQzD6vxY5o3DA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b1FsNUFzY2NmK055THBx
        NjhZVkpiMHBkN2k5WEpDUkpGQnUyNzZ6SjNzCi9vdVQ0SnZyRXYyRklTZStLdzdl
        N2RUWnRBUG1uSVcrWXlYRkhkWTFpbTgKLS0tIHA4UGRkUnFRYUE3aDhyd0xXd292
        YmZENHNTV2JDeERKVjhFcnZUL1N1Y1EKBt9ZSBP1Vqoz8ShjeplvY6IvzcleSdlS
        hfIJR1wen/u/22gbxe0fePcg4LeeyYWZLcvVtHeLZxFqHUxoFzD1vw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T17:30:42Z"
  mac: ENC[AES256_GCM,data:iA1bSPcuS0Z1D80sAgqumUgzUhWPeCFIMU4squeA1DifNc/6g4HukgLLBnlMh7x2XJVD9XqPKKHIxkOtF3jNll0l9ro0dVWBGP9IUyKhHIUbt4HslwFEdPheHZR6JNiMa1nh5TMZ3ZnChf+qt1zICzJFewhnNmX29axEClXqTRc=,iv:5s6VSfUHBj7mmBhIMBLrXIZIEJqP8OF+YpYBrnqnIo4=,tag:7FjyvlZlISDQRRQKENEc9Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
