apiVersion: v1
kind: Secret
metadata:
  name: coder-workspace-git-ssh
  namespace: development
type: Opaque
stringData:
  id_ed25519: ENC[AES256_GCM,data:4IkleTfiGtYjhoehxgIDKm+gvbl/pF9c9j0HaoElNxxXn7lL0Jsi6zQPng+K06bZ/GJvGHhpfWyP86bP96ZhpRxI8RtepgXj9zYYdaYrwvh2R1IU4F17mAKyLQDOGXaVA/mOhSZPgzZ9yPXQXZYp4v23yLgq/STRIijjK5gvfp8WWLjzhvsIc+PXZRJ7RxSz06kHKK733rXbKb7igOH9wgwFRGTIYMjUolFhW3IJeShDkM6OsJhjTbAf4ke481cad5G4JW/d0UXq2oOkwGoVrxK9kztfiN9jlQK/obkd+ENnJPJ2sHYE48zJDgvOv083Qqt0cOOU7VlHFDoVoSmt7Op6cM8/qetOx+VMPAewHmPDUD+dYj0wrqliaFMQBr1/iOo9HhN/GrbT809hEVZ1PCyCFEHml7yeKUJ2BGYxpofj3l8noh/2JOO8zsSImBmn/gIw48LXJSKF5Erm2l7+qkoytIQZf05zDToEiFiLb8psZwJhno9ehBSZ7eeG6PzUVUaWZzP7mbLyY5qxkQ3o,iv:tdRjU5E7F0ojePNYmmDdFFtDH/ai/TWD19Q8kAL8mUU=,tag:yUvxW56M6t1b8Q6AOaNbMQ==,type:str]
  id_ed25519.pub: ENC[AES256_GCM,data:53uTZJsFgxaIIN7/9pJLeOrneuacqrKMNC08ODywPSphLpRcd7yq0iC5SK1Qlckh12kOpV1OlrKmUcCLpV52ErKsB6qFUWzMEq0AR1CO+wmvrtDRLuFTlId2qGnj9A==,iv:kusfGdx59+mqlKzMj2Y7F1wfFTnn1Q0ra4jcTwoV6YM=,tag:D7LIkp6VaLxLsU/QFxmyHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS0Z1NHZndzdpWE5xUk11
        R0RvcTAzeklZRFBuby9pSUNMVWFDTko2RWdZCk1pRDZ2R3lqVXFuUm1CdFQ0Yi9z
        L3g4WjR3R0ptbUNGRjRsT0FlTXpVZEUKLS0tIHpzSUFhbkFwZGVzam44WUFOeVZw
        VHdDMC9HOWF3bkZ4bHBEWWZqTytjS2sKW+3R+Dyh/V2CJ4oZx43HPZ5qlCEzQvaC
        pktvvhcL041VU/FuH+Ko+KunQbyMq6M1Zdyvvr2X8cTkrnc9tFVuyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T11:53:45Z"
  mac: ENC[AES256_GCM,data:Iqecd4vtvyRQmFTzhtwRVvFZVURq2NK1hs5gAXy4ixLe9XdJ1PD5YGKlostdAAFG/iZqhXh1mEEUiGSfforKnfkty4LUHiqhwtD37urYdCSL+MPm2L8SacDZbNt0BWGuZJn1ipfJ1H3tHBcKDzdbwa2k3R1KxCgwuc+Us7AAmfY=,iv:CJfaHxk2+BM8nbNnu0s4Y5ylb3CGma1Dd0n3ARoXe68=,tag:jbAf0jtMyHv3Q1tqfB+q+g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
