apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UMNX26cHqkZBwzOsgCTQ7HxX9LRAhIhtRrA4d+ueYiwPcvJxKaU04A==,iv:BBegTsK1u4I0t4XUR5+sSNDuHfiAGVVsrbCAE+DZDdg=,tag:VM00Ev0focJ8BqToZclyEg==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaWFDbEZxQUdhZ2hNWWVw
        citOTngvOWxWc3dkc1hHdytCekFFazNOREFnCnV4U09icmlKL2Y2OW5hNDV0Q0k2
        aHBkSlRkMlMvOHEvcTRWYThBQXh4c3cKLS0tIFlueC9rZlN2RHRmRGg4MXZPV2JY
        enJ5SU1DTGJiMlRGMUR6YVMySThTcjQKXKTcLK/diPuqmtoVslj8FAkylctb4k6r
        17aCzHSv2ae4vr2+vD8ghHm5mVEU3tAPAyXl4sj8GGDr3HIv4mzaKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:51:10Z"
  mac: ENC[AES256_GCM,data:Ixvaa2MWugDaTzPW9aCV6Xr/ItQLaOfdHBwXR33njv7eXvmY8K9/JkR3p+yzgxpB2AJpyaCcos4UzaZrJDXL/hfuGV4dXFnk6Jp7uBPgK+pJfvRt58Mqy+Q4zsDygZQwjdUocIT0st/Cw2n3Ij5psI3Enn+izytV/qVuW4VFP0E=,iv:pwNMikyHPqMIQ87rltmxuQ/cXLeTF46mf3ybCoHIJow=,tag:cb3GtuYBEf3dkz/GUN2H2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
