apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:/htHgfkHzkQ6hJrhJ/cx+K1vxxRitBSosy0zusnbiPMhboj7OGDbuA==,iv:YupJRY50L9zuoP59ulprNhzcsL8S/2CwEHLuDZKdsVE=,tag:RqCpYfeND6x1rzOXLwaBMA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5blM2SkdEQUxTUUdmM2ZG
        N2wxaklWcHAwUm9rTnpINDd3UUpXazJGNEhNCmZTbTRiNFM0OGV0Q0p1WHg0WDUw
        VDlJaEUxS3p1QVVWbmpDeXE0L1JpWVkKLS0tIEg0WSt0RDlmQlJZRU9ZSGkyMHVx
        N1BnQU5FaVU2aDZVcnYvdXJrZ0dLejAK6pTjuNU6ONP3kcSeA/sAnNISqs47G7mG
        PWKNLWn8p62HBr87PtzFjZ7SaZjLHLZ6wRrQE/L2PqDdiZ7t1HwuLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:46:05Z"
  mac: ENC[AES256_GCM,data:jwpC0KfHWzCjlZPCWr3yfry8nMOEP5R0wONNrOB1V6aYxgKILNq350JGY2a1Bs+7A8eBTlVsJLAHczlUxkHeVifQIkOppmdM7KIymFN6imbPUu3X4WyjTKof4I1av3fNEHxL7Pn+GMW9jHzADpPeePhfOHPBY1uIZWxl2s/VWts=,iv:V4C7R6jtFLQcZ2JS1WDXgSIDertAMrogeOVI5tZ+Nic=,tag:Y7yG9Cym86nfkAecW1CNQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
