apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:RTgQUO+Km4AlqHR/S6QVdZuZXPWDDjzrUGrECBKtBy2zSjRfiiuG2w==,iv:/vjwOSBh5yO5YjxHGVpZSGQt6AhjIFqwRbVcw12uRzc=,tag:onYfSbpKOwBPhML8qrox2w==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOFhCZytGS3VjTlg4RzFP
        aFZ2YnVjM0FEUER6cjJBckxJZDJZTHBrUVdjCkxPQlNyWDYvM3ZEc3lpaEZGZVpx
        Z2ZyZWZLOHl6RU5hb2Z5dXFHbUhqbG8KLS0tIC9kcHRucXJlWW1OclNReVF5VzI1
        eW8zRlpQZEFzSm1Qc09CZkkxcSsydmMKrbXFgs585pljaJWw1q1WYuGfYy1Xykoe
        iwXIx4NhOLrexBBruZOIJ1SE/sj7YSWPEtjBowcZfSyI/OMTm87PFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T05:08:06Z"
  mac: ENC[AES256_GCM,data:SqVUGo3z3MgFgV2j/tABkNKKb7GyF5WtwDvQZ/8W+7Nu2qCVnYbrovVScsqZ02e4S9UARUAv9MK6JsIOBTHLqREETfD90VwdMFEEYqnJ7khUEEd1T4hS9cOmfOcl7hZJyhm67TEXzp/vTJopIIf4Mntk2okSCA4ZDwoZjLu7m2Q=,iv:P/fZy9k2FRyNV+jLgW7Rz33AraJxQ6xYyE7DjVfWuds=,tag:oGZoC9OnUuIozAx1wasUKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
