# CloudNativePG looks for two named secrets: the superuser one
# (initdb postgres role) and the app user (the role authentik
# connects as). Username/password format: standard kubernetes.io/basic-auth.
apiVersion: v1
kind: Secret
metadata:
  name: authentik-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Dqkn4Rh+wXU=,iv:NqiP7PdCe6FWpQ6Z66KD8+t59ImCLEK5pSOBNz3XiPA=,tag:4EB9sKmwpyBRnU8gTx9GZg==,type:str]
  password: ENC[AES256_GCM,data:cBzx82YfV14hqcXosfcOHJMpGzu7vzlX+gQxvqlX5dindHmtRgjtHVTc/g==,iv:b1PmYDVSFebjFObNms4wRdBDsP5a/xSIwAetPzPc7E4=,tag:nRbr5QVAmnkDhkqmfdWqxw==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR0VLZlp5S3AwbnkxZzl4
        M3ZROFdjQzRwTXlKYmV5Ylg1Nm5mQTBiUURBCkRXZ2Q0OUNlcHRlZTFjaDluZHlt
        ZGpCejd3NTY3a09EQjNSQS9FQVQ5ck0KLS0tIHkyNS8yenpxaW9OaWZRR1R6OEY2
        dzFvcGdKcXNUalhpbHB5ZVJqM1ZhK2sKd5GXY8GBgypicRXURtCUL+26MoskfJ04
        SO+H2zfG20DOcJlprmWN6dN6qWZzxWS45BSRU5CHpGkOK+mwDs8TIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T08:16:56Z"
  mac: ENC[AES256_GCM,data:pLWNd8XhjAFWlPcSOOpirZ+TzrOF8+rmVlX+mrfDuxRwI14Wh/p+pRrVqdeDtomt3DFEKLnl353ni1qKA8iUSlvo6gwO/PpnKjFj1Ta8gKKpIrOskI8iyLMhEMOmps8WQqyaZ7rmuKKZjMPwZdghi64hUdqioj2akEfRPYNOiWo=,iv:O+H0q564a7UXRO4P3PUk3UshpUEUF0ogmLq7DFWH2EY=,tag:POfAl2v9X9OqZgaCc8I8wA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-pg-app
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:LAI130dRFWOy,iv:MAsWN53spyZwvPhd4vk0qAKdioDG/2zoyv/1qREjRl4=,tag:dHcESAZr3KepWL6t3csLNQ==,type:str]
  password: ENC[AES256_GCM,data:bBDbJWAsY/FuPdkjcKf49F7kOsQVPpcG6Pk6dgRDpYCrl2xr5xUmmr89Yg==,iv:2sP+0Jy/9wLmBaZN7GhERnphwDllstzDFDVL5z8OBdQ=,tag:Zr+04yVyvCRR6wbdd7SCAA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR0VLZlp5S3AwbnkxZzl4
        M3ZROFdjQzRwTXlKYmV5Ylg1Nm5mQTBiUURBCkRXZ2Q0OUNlcHRlZTFjaDluZHlt
        ZGpCejd3NTY3a09EQjNSQS9FQVQ5ck0KLS0tIHkyNS8yenpxaW9OaWZRR1R6OEY2
        dzFvcGdKcXNUalhpbHB5ZVJqM1ZhK2sKd5GXY8GBgypicRXURtCUL+26MoskfJ04
        SO+H2zfG20DOcJlprmWN6dN6qWZzxWS45BSRU5CHpGkOK+mwDs8TIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T08:16:56Z"
  mac: ENC[AES256_GCM,data:pLWNd8XhjAFWlPcSOOpirZ+TzrOF8+rmVlX+mrfDuxRwI14Wh/p+pRrVqdeDtomt3DFEKLnl353ni1qKA8iUSlvo6gwO/PpnKjFj1Ta8gKKpIrOskI8iyLMhEMOmps8WQqyaZ7rmuKKZjMPwZdghi64hUdqioj2akEfRPYNOiWo=,iv:O+H0q564a7UXRO4P3PUk3UshpUEUF0ogmLq7DFWH2EY=,tag:POfAl2v9X9OqZgaCc8I8wA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
