apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HvzlWtgZdP+3U6M=,iv:lulXVOJF0D5oWCVtl1wMDZBP0Qmt2470rYox7j7E+Kg=,tag:8RLKhxJE9J1YfdVxWnV9eg==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d3FDM1VZSlVuUUg1K1Yx
        cXhlUm12WFZyNkZEUUZNWWlnMXBYTUJodFY4Cnc0OVN4eEFIK0RSc3JkMUNEVmtD
        VkljVDZUWVNTbWJIeXpGTEpvczFraVUKLS0tIFdKY2VEZWFaUUN5Z0dwbGdXWWVr
        cEZVY2ZMN0VkOEVZbS9qYVI1bFkvblkKt1FTkgw8dJgVU5eZou06+tjWJbxZfEQH
        9Y3OM+yTuZ4h6gTViof1dkFQyICTAxGjg1sQzdlBqqT/HmbxrwJmrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:48:06Z"
  mac: ENC[AES256_GCM,data:XdLQmMezW0CD50VUfHVN/jpM3NAvjAsZcB+qSnxsr0NOCf7lSZw9o222PRLUQeoGBYzql/FGcgWXECzg9EidcF7dUXIeaKRczXPVnMm7sUjxP/2fZUcTs+AQV2RnARB0SavXhjB5FSqxdMigjiColyY3fjDU1R03G7aSQ3rcZHE=,iv:iaxQpHsH60G4TdTHx5ehJdkKsVkr43nMwGz6voyHIEg=,tag:XloZpMZAyr8Idm+J0c66Rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
