apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:pyv1PByFtXymyTE=,iv:BytqN0Ggh3RFkW8jpB0Xb1gWsFcUvse3gek2RfFvGGA=,tag:SeMxEeJ/HSDScLOWOQRK7g==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa1VmOEVrKzMvb2dHaDBE
        U256SjZFTU1ieUh4bGZ5ZmZReHZ6ZFRmOENjCnMwSjQ4VlVPOXg0cVhUSnhDV3ZB
        RlFFOTVUUjF6NEpNWVJzM1JsU2NYMUUKLS0tIGFSSWNyRDFOMjNSSXVCZ25YSFFv
        ZTZsZlR5NnlQS1l3bVJ5aCsxZFdxYncKb4SV4cMJYW+tXviZDVTuW97jAB9TEr1g
        Rbioz+wlzpukpygYaaHQBsgEkIDQ3vCMFliJWjAb+kRHEubgHnjMzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T06:13:09Z"
  mac: ENC[AES256_GCM,data:MFJ5pLqktSypYEaHZTadajWlWDR3zAPVL2Onz1GDORznYmRuCjI9bwcMKdzFmEXmT7REobTcE//2pvtwcRFiXEcjVLg84KgRSg/eVuTGl+xW4N1LonA+ofu2f4HtgC0t8Oj/WFg1v5DMK0aaotK6TCqRJsezCHlNzi/GocobCOo=,iv:MzKDLpqsQlDnpGA5lXHGpGbo7RGYaz1QwwjWS7nLFos=,tag:CWtTWt2GoisOLbkY+toTYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
