# Override of templates/config/kubernetes/components/sops/cluster-secrets.sops.yaml.j2
# adds the locally-introduced secret variables that aren't part of
# cluster-template's stock list.
#
# Add new ${SECRET_*} substitutions here as we land them.
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5qKVAyfp8++vaJU=,iv:SabX5JLrIESStmpvP5mewtkAnbIGnPienc/iFiJ9ulk=,tag:N4kYjPWHMuXu2/qbaWXm8w==,type:str]
  #ENC[AES256_GCM,data:gQevfBvumqKmo/ivGIUdb+3la/G6X3+44GKbaBOZKTKoY4JKO/lBY545+G2UtdzcbM8Tdt+xyql1,iv:gGgDtMP2DlfOusHus47+ZY7LtejLtFkRU+Dn6xQ4GNY=,tag:QszuDIauYfxNyOaZOGMKHA==,type:comment]
  #ENC[AES256_GCM,data:0pMj+Z0LgVUC1Jg3T8aQklTRkBMARReBGrEVcPAITtF+Xgx3LL9YKODzSTvYrzOTpMQ=,iv:l0gZcc0YDxpkPlxfH+MlMDFBVLCMkQBVoPa44MetSV8=,tag:SGe5ItYMvH0WigkFo+pBmw==,type:comment]
  SECRET_TAILSCALE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:071uI7h8HaANkbjr82L0YlA=,iv:4JsJLvd7Ml36OcxFpkvwiHfRPzJR0Xr8yrLm9czc8No=,tag:WFB6yNwK+E97NiZbk6UN9A==,type:str]
  SECRET_TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:p2JzZcz9fYAse83piWE32e7Gm/VHZhL58d8GMocF51djcdN/AukdVDrgk0CZ7j5YycYsublHOTL8hStCoC9A,iv:rHNAPdpXbdXaxjxAf5P8SJOSPX5nICv+QPj5w+rTzKU=,tag:tbJ7nLTsEtVM3DdZ1JbF1A==,type:str]
  #ENC[AES256_GCM,data:v1r5I+nF3L9cQGgKfa63QMptsg9YtyQJOtp5uUdAOQ1fVc2yTS578lMqjSyt21tanny5pSlKgA==,iv:jjbY7rFnXSasoHxOXAQR6y6axOOasydjSJRM+EQzOWg=,tag:tfJnOnSfFhdNzbPxBMMZYA==,type:comment]
  #ENC[AES256_GCM,data:tJkUQWzmufD7+3WvZg4F/wTrUI1adCvhtDd4ikom85Fq/8MN8GB+OmlQwfHWigzYox/T0vLr8ydEKz9Z,iv:/KYEklAtJ5YfQr+thb6dXA8poaMuDKX/XrVutUD/Z4E=,tag:XKtRwNwcrR3XeWE9naSA1Q==,type:comment]
  #ENC[AES256_GCM,data:s7XQW6kB4uVBxvMmliV/SdBhjnSrXIeibFNuWo7lddJzUTRij40RGokZA7OGKNjc7hyB6islplONzbU=,iv:mfnEGsULP/1YnHqPKuB2Ap2eieCM2eFPlNz26TgPsc8=,tag:6EEXILuZNSKTcPaPZhHBhA==,type:comment]
  #ENC[AES256_GCM,data:VyPFcmreVVBEujH93+lKHbJ0TNF/XFwRKCym2y/WdT22G2/tXegUYU8cNBAD306khQjliXpimg7WPco=,iv:p+PQ2HB0NU5FE/bSOA5I4D9WWl36sOVAJiI5mDrfKdQ=,tag:oCYJeaMVl4vbGq4m3VeTfg==,type:comment]
  #ENC[AES256_GCM,data:8Epx5iVAErGCCN0WZHYHTV/Is43v90zSA/mgTo08EzjxTGuvFnKP77cqnz9DcNZIG24ot2cZHw==,iv:54/RptZ2FDI8GfYwHegWz9jP5algz5Sq2aiNJNUmJ+U=,tag:/BXXcWsxfccDmge8tR5WnA==,type:comment]
  MATRIX_REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:C9AxhORaVwpGSVE/kFgGKIcDSnimJcjoJ15zC4OAtOs50YLMEYMxQD1sT45Id+SbipsCHRNeIqtCC71uduTEHg==,iv:SblHhfMQPRxc+bjnAcqWGGegKthf8eoB1zT9+tj/oww=,tag:Nk/77nrkzY8KZlm07AzaqQ==,type:str]
  MATRIX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:mgarcQS2LM/ga/1Pj4t6wHOtQ9cllJl+Rx8GY+UjuBbwB79yVug3vg==,iv:sR0F+99qDQbK3LtAczro0nIJIIBECYFbfCNnbCbkin0=,tag:lkRGBWNr98ah4fNlgGt5jw==,type:str]
  MATRIX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:pgbhVkj/d8BUKg+GFRunT3bjOGELbdNQRgToX8OrQjg=,iv:/7QEX2E/PVmaFIkYkplfS+jPNxN8DaqRtH6Q9cNs1YA=,tag:A6EIzXGFH7OxzGlIoznPNw==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RlJwRkFaeTZkdk04NUN4
        dm1hLzZEL09sdzc5T2d4UUU1UjZXN3JkSWg4CndlWTZwNTljdHVabTRPeXpjK1or
        bFpZRTdiK05jWmNKMGlXSzBHQVNjTDAKLS0tIDhtTWp0ZTFhTDJJLzBrOEcvbTdM
        Q2NtSWoxeTczNFM2VUxtaGFBTnVkMDgKW8DvEKwd6gmeTr+bp/lvc3J7rC1GkqUK
        WQrrMM5bOyO0BUFH12Eyz2ZMvs1nCk1Op9P2ZPBbDLRjL0XMWOzgLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:51:10Z"
  mac: ENC[AES256_GCM,data:ymrM4Dk+aV5F6p69FOCDJ3HMK5MeS3Wi/gR4qEe5e59q/721Eh6SpvUMnDxCE9T6z/LNh836uXcOHduSIZuULcLcnBRGEadvyGy+GwiHoSKMi6xK2lcyZkrlWOVya3WppzLyfqN1/hEOODHcAGBW1FF8Uzyu/MYUtakAXDP+dqs=,iv:2isAwc48GBVt2Tf7+AvMK1ICZmtXRdYhq7YtOJszOq8=,tag:b+Wl4d4f0iI/C8FkNNsdvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
