apiVersion: v1
kind: Secret
metadata:
  name: litellm-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:AS8xq+Lkq2I=,iv:TVXx1djRGQliC2LOPTKCkgtE+0aOMqn9hKyU7unCB3s=,tag:vjezbgGJjy1gIBccKt3kqg==,type:str]
  password: ENC[AES256_GCM,data:ANUZkP7y3jWCAtB585BaJkMhH+CKA7aq3yRWig9QFq7u8egB4i8q0s2eZ9/bawtl,iv:A5gh4SKdFpRXjxM00DWlQKuzgTv7uyaLxTjcv/sIfTo=,tag:ddiO2NsoX74dfxCot5zs8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cUcyVEptaWFDNlkrTVNV
        MzJseFEwOU9WWlIrMUFXcGFTTzB3S3NmcTBjClUxN0VyZ3dnVWhQVTJoR3Y1RTBW
        YXVuTzUvM1hRSzlaRklkMnlKRWlqVjgKLS0tIDhteVdBTjlTT1kzUS80OFQyQ1hH
        QkNiT3FvaHkvNjdKQW9EcTd1czZSVjAKdEFwcKkIUyIHQBzDeg+NlAWkIAnIqDi0
        0ThJli9vzfauUqReACCOLoanp2of5YLGphjeafVB84Q1dyFWAZLehA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-12T09:04:06Z"
  mac: ENC[AES256_GCM,data:F+AnLQww3OponRUDmRHHbgpXVDT8C7dzyL4jb2sUWQ04KIxSaYfIO7r35fJTjpobw8E72Gff7woB10D8wKE/BBs+se2jyVSUVME4IspANJgIgR83JAgvXHNpBJKMV6ZMZ+0SBwGuNuYkCAZyQBSeoR4qeN4jRudK6+KnC/d4WBU=,iv:L/zfymVM/CkHN/qspSixf5ZGfSqkQyEiRc3iJeejRuY=,tag:7zBm5ZigPglOwt1SP/V5YQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-pg-app
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:sqCxcdb+wQ==,iv:RkBGblfFBR8bwIbyTzWMAX4hzbpRAi7iHk/1JiGxL1k=,tag:85/7ks0VkdLwaGqK6sSAfg==,type:str]
  password: ENC[AES256_GCM,data:vfDQ2x8yiB9gHwn6SwyGzaquu8REgcXgL0pJ0OZe5OV46bJ54xCG/1wWIKMaH7z6,iv:AFpZr3V7oW2lKqknApA0ilW6Gd+YOil+MjAHlfyq5V4=,tag:O+ucVfRnlJrCd0HkTrNVQg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cUcyVEptaWFDNlkrTVNV
        MzJseFEwOU9WWlIrMUFXcGFTTzB3S3NmcTBjClUxN0VyZ3dnVWhQVTJoR3Y1RTBW
        YXVuTzUvM1hRSzlaRklkMnlKRWlqVjgKLS0tIDhteVdBTjlTT1kzUS80OFQyQ1hH
        QkNiT3FvaHkvNjdKQW9EcTd1czZSVjAKdEFwcKkIUyIHQBzDeg+NlAWkIAnIqDi0
        0ThJli9vzfauUqReACCOLoanp2of5YLGphjeafVB84Q1dyFWAZLehA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-12T09:04:06Z"
  mac: ENC[AES256_GCM,data:F+AnLQww3OponRUDmRHHbgpXVDT8C7dzyL4jb2sUWQ04KIxSaYfIO7r35fJTjpobw8E72Gff7woB10D8wKE/BBs+se2jyVSUVME4IspANJgIgR83JAgvXHNpBJKMV6ZMZ+0SBwGuNuYkCAZyQBSeoR4qeN4jRudK6+KnC/d4WBU=,iv:L/zfymVM/CkHN/qspSixf5ZGfSqkQyEiRc3iJeejRuY=,tag:7zBm5ZigPglOwt1SP/V5YQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
