apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  litellm-master-key: ENC[AES256_GCM,data:DTC3efirPMVQiVWFl/CcaZsnniP7NtI533hnxe1gD98Lw306iIBkUXyEc4yDcpSp9vakY6kPsAJ0DZU=,iv:iy0g1KcYuONuAi5eEm5f8DcSgm82WR3/Z1gTxe75VEQ=,tag:Yb8ypnBPp8Ve5bo+7Xyl3Q==,type:str]
  litellm-salt-key: ENC[AES256_GCM,data:piTk2TehjFV48JC1BD9r2//upSX6PDzTXYWyDjeqlfrjgtENZf06YnG5GxB2f1N4wzuLThLNjXCbWmkOv011Vw==,iv:rty2sPm9cKFEwj2JmAoX2ADt9SFhy7v5aP1zkfBXhVc=,tag:ypEdj25oFXv4J7D1AcWjHQ==,type:str]
  ui-username: ENC[AES256_GCM,data:xbunuew=,iv:H45pkTNIRhZYuiS/GpKm72b+rYSF7b2Jz1kE0dXB5r4=,tag:tmIibf+YcaxeN9sCJtnGBg==,type:str]
  ui-password: ENC[AES256_GCM,data:grZBrkjfB55e+uoGaEA6y8kaGejSRlbiRyzSK5jLlrM=,iv:deUmZ2zrY0hjDQCS9THYhbXvAPVyYDCPIV/NAn7kH2I=,tag:YFc+/qLNAVoEKNaufYVzfQ==,type:str]
  deepseek-api-key: ENC[AES256_GCM,data:3fYUJBVTBmZ2jdiSOeUvQvupqeyp4aEodgXQZhG/0cEXqgA=,iv:IHIqWu/qxQljRjSK6CyRo6Ocn8ZGRFUQQ6xoZuqmcis=,tag:FbA5F2/AtsDsXWJcAqpqAQ==,type:str]
  minimax-api-key: ENC[AES256_GCM,data:B06FGq4ife0dMV2Pf92NNJdmUsA9yPrZbfNnp0tFobgYZhbnN+bmr9FilDNGPc7aH75HmMHYbYgDwHrpYrLHbSH7YfKA5GHG/BHy/Xo1f97LBpSvyeRWONiq//GCyn2GawwUJ6/Ado4naYvdIiaUKslaSEOmKg==,iv:UimAIUewcAiAV3olYOisXoO6E1vFuaGcS/T2BsJ3yek=,tag:TOtXcX6zO6G26Jk6nwkHpw==,type:str]
  moonshot-api-key: ENC[AES256_GCM,data:gIwYpoadRKX6hj0zYbinIJqkQctiN4/gnGJOHbw/lcGtQY/qvQEsnj50TOe/RQilLGCW,iv:U4iH9kwgCR2wdxwEUVfgSU9ECioCVPxjRJ0n3j6t2oE=,tag:PRU4STJ5HSu+qSeobv/g8g==,type:str]
  xiaomi-mimo-api-key: ENC[AES256_GCM,data:u+1Cn5wevg0JrzfPxxnfp6jzUvEx/HTEM05og4XIO/LNCJGH+1ehnDSZKLhJTmpQPlyC,iv:8Xo0s2H1o0v5uHcexUTHCGz4sh8JCUU8fPrNEn6W3ng=,tag:sALi9cBCN28NN5gSJlhiGg==,type:str]
  zai-api-key: ENC[AES256_GCM,data:/RP7jADk77XzmEzIL2Mctst42Q52IU1Y1iqtO8jMRGMPBSsxckv3ugNgbhvl5rx5Lg==,iv:lCwzzNJXudVa3fHTeoZcG5+t6AqUZSm1rkNtDPi7vy8=,tag:4b3pH9KHmx6t2tTUbO0cEQ==,type:str]
  openrouter-api-key: ENC[AES256_GCM,data:JnhtcEjw7BksV9/EIB00txQJIBa8sfsLzrZqI0SOee0CiWJbpjffdotQ5UXqIvXnaZK2n0gOX4nMB35WCY1rJ08GqDA+EF+qOQ==,iv:8AWeorVR8fY3cjzKDvF1G4jIlwc03Bw4NTBx34kqMAc=,tag:TZmRspV033+icGJo8fV2aQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN2ZCaW5iU0d2djBDNS9T
        WFhBSk5NZ2ZxaVJ0eTk3d1VwVkZWVHIrQTAwCkJhMWRob0ttcEJYWWZTYnpwTWpY
        ckpXVHZvVlZ6OWp6QWxOWEhOc21EQ3MKLS0tIGJUK3BZd281Tlh1eFIrNUpsVWJu
        WnFja21hRTY5bTVycUJwc2ZUenZuRzgKGBuIgR4yUHMUALlYuCzMrERJjxNRUBee
        88uMCLw28trRRZYWqNM4WoJ7nuqSnoiRWuIPfiC30TiKbq/45LCBAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T07:26:13Z"
  mac: ENC[AES256_GCM,data:Zo0ZZNHMaCs/kFD52t+DJBl8Of4pIThUBCIWMfWV9oNHwGxQipXkLKjVTXkONVnqyAdflm6MzT6nxjA4/kfptzauvdrb3ooP8Y3SKQgLPDmlVQ+j80jT19l/4inJDWeI5qSg9zuI1Anc+JSVjgoL2sI1pQxEn3jAbwIT/LJktVg=,iv:Rh7gB502OyJfDhrwMknfDHiIO2uJu3kIRK3KMfXDR2w=,tag:zSdRfbAks6ea6ekoUL9iLQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
