apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PHyKkUd6zIA1CDC1D2hJvGxF9dwpNCWWuzP8JE3cSwY=,iv:FIgBOaoByAYC1IVOktyWVNznc3lebZd7gZbJU7VSaqM=,tag:83CT5p0j4WG+L//iMfm+ZA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ3cvekJXbjc3S0tSSkNu
        cURFNDNuK1RQOVFURGFwYkdCS0l3OXdpSVFzCjBFZmNRVkQ3WUxmRkRmVHRGcitu
        eVZwT3BqaUM4QXI1YnFMQjFmUEk1K1kKLS0tIFNTNUtsTDJIUkhwdWQ3T25yUGcr
        UExteXdndkZBamk1K25nQjhGazlyblkKwuvV9axs0jydkgrf3KMHX5QD1EEWpEvi
        zn9aMOExr62qrvQ6xJijPmFpFNAFNi4gXxC+c+6Ah3m77egNcKam0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:17:55Z"
  mac: ENC[AES256_GCM,data:KnzjJkqB10PIkAjbTe4kxLY21PE0AdhiMnyYM44h8awUIH3k/OmEjP4nSWVP0utEpqBM1wY3EmnD6fQfkACiMaEGfL3PfbqIb6gaHs851IFsEvyxvYcWdQ2bhtHnAsU7zp6hrjvbF+AKiiIxErsvtwLxdUaitmGvSvoLeKIlhds=,iv:VkoiX88U/IHSW1C2GhOhtjLFTRM7I4Au7wp0fL3oZbI=,tag:H/bJK1UbWRKPFXdRRTXScA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
