apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZKHjaS/xzt7dxwGhvCvPNMBa4v0QODcao/nCTeF6lXM=,iv:oTDXKk0xIQuRKUro4U4YCRXawAShKg4rTjmn4bPXTiM=,tag:pvGXNsT0vhYTZVfRsnqnvQ==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVndIM0d0RVdqa3cwd2NE
        eGE0cXNzOUNpSHREUFkveGtQS0MwTGpIYnl3CnRMazVkOGtMc1RKSmFOdkJ6TW8w
        VEZwUmJOcW9HQlpzNHNsYzIwNEVPcVEKLS0tIEtua1ByRHduelF3VTYwdFlyQjhk
        akZLOXdVS0xQaS8vbU1VTkYzZHQrencKOJwKg1Oh4lrCUaBzx0Ml8D1TWW8O79AW
        UnVnqzVn66W1kpHUGhsYcM18T5WI8oLpN+WxUE6FaxWJRLjNovp6Cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:48:06Z"
  mac: ENC[AES256_GCM,data:4CgXbsuE5g3sIAL9g1nGkW/q12Q4iHPelhJ8psuv2rf+KRLSvbzNplYZjw7rauBXet3hpJh01ed3vxdMaHnG9T9d59cSOiwIEwDXc/0z7KMe/Nc0E6JDIPjiNYNZDZVwKrPFDm/BaP843RDtSraqny7AWPaQVtEEuA9syfGkGhQ=,iv:Ztes+QedrvFO8+qzz6BVg5r4CGx7K3iLVwHSCuXT/+I=,tag:jmEWhcaSz6Cs54uArKp/Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
