apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:mz9kWkwaRURqVFHO0KZK6QvahVl/FV6HC9teLmJpMIA=,iv:izY3mMkF4GHk/OKX/z1GDZpgm73LLO+//kpB6jEii/M=,tag:0W0iKQF+I45FnYBPqBOjag==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TlNyS1hjOXVRMkNzVG94
        NXBPclRtVUtRSEF0Y0UyUXc1S0VSeks4bnhNCndjUG41eEo1dDJhc3h2dUNoQTVM
        bjM1RVc3VXVHeXRQK0xoU1N0b2NBQm8KLS0tIGx0OEplNWNucERyME9VSVorSjZM
        Ni9kY2VEb00wMHkxb3NCak9ZZ3lZckkKDfd7T8lF+lAqfOmODtaGZpzG5N3zRHy+
        xyI7lPhgRrqPuEumiJPXqRFyHZa7iR9FWNT0BomHmT2MB3X+VRm/BQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T05:08:06Z"
  mac: ENC[AES256_GCM,data:871HBClinAh8Q0cWILtfNLfTs8SSasqUxK8jOnsB1ZLf5Vqr3fA8QyPNAksKv534BLgt8SINzSOa4/V357/goi1jJ5if6IsJBDz8HktlokJ/eqfzOdQIOmOewom+iPEKgEeFJVb2UhfY45HF0zQzVaWGfdeCmtrjRPKcf2P4Wxc=,iv:wL+TBC+2PVr1wA7FjoMjC9otOD78TeMqMLbJb6JkcME=,tag:msBnAOZ/77eqZ5dp8KUfuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
