apiVersion: v1
kind: Secret
metadata:
  name: attic-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:ihWTPO3OflM=,iv:Q7KMfsvRzza1jMrpKPLPb1p6+x3JZT5oBzw2zB2gK0M=,tag:r1+xpNm4Y3ESjPdYfalQOQ==,type:str]
  password: ENC[AES256_GCM,data:G3iWI9FzFDlQxAL3F+TS5iolFmE4xd8HquRzYAwlEtmTtZNL2mHgQg==,iv:zJb/mwUxqyfsu68D0Wf9UnnDURyE6Fzhd7olheBpsoE=,tag:xUoUAOZq59RRw/TtKcU52Q==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTm5td2VJOUxxQmtaVGxa
        SFlPVjZ4TGUzZmFhT3k1V281WEluNDJibndFCnJZbGxyeUp3NVF2VXQvNnJBY3cr
        TTM3QSthRDBjZDE2RXhUd2J6cDdpUGsKLS0tIGpDWnJ1NmZqWnphTUNocTJrSGJ6
        QzNkcDV4eEkyMUFPeS9ld2NpN0VQbzQKAoYBPADTkc8zDnpelMV2/W6aQBqMb9gu
        KV2TqNTUW2sviSVbrEETSqzb8HPEhmC9t3T9dfBqEyU140RLZKBOMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T16:07:29Z"
  mac: ENC[AES256_GCM,data:4ButUjNXf822iHOcSwye3nTtZC1mOhUplURXHTJgCuXh0UpXLncZFpZ27TzfHQby/hBAgCud340m82iaLraFjriyC6QIhZQfqL3nEEzfY8jhOgntfuuTudM1FMRvYsDcH4b+u9axSsLVm5vas+6W0bhk0mNLnJ6PAxS5i26Cjzw=,iv:FZznD4d+4xLcnBId/YnGynEQnDgo675tu/ojDJABbHM=,tag:56uMooLtKkwfTvyjoeY5Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: attic-pg-app
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:X/fOfRU=,iv:/YZqApd3QIcl8xrvVFFj2bE4okq7fyN7pWGoi0p5Y2g=,tag:fk47nh7ZGblmXvDXYonREw==,type:str]
  password: ENC[AES256_GCM,data:Suh4enFfkGWIpTlXYMfatfhDRFU5Z6BGOgJJArj90dLYTfMX0l6kIA==,iv:MFmdr3XIQXXiNkJG+/GbWSKG0HwaJg/VT0ExOkRAGhk=,tag:p2oMaADM57EKZ7jiIKaWhw==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTm5td2VJOUxxQmtaVGxa
        SFlPVjZ4TGUzZmFhT3k1V281WEluNDJibndFCnJZbGxyeUp3NVF2VXQvNnJBY3cr
        TTM3QSthRDBjZDE2RXhUd2J6cDdpUGsKLS0tIGpDWnJ1NmZqWnphTUNocTJrSGJ6
        QzNkcDV4eEkyMUFPeS9ld2NpN0VQbzQKAoYBPADTkc8zDnpelMV2/W6aQBqMb9gu
        KV2TqNTUW2sviSVbrEETSqzb8HPEhmC9t3T9dfBqEyU140RLZKBOMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T16:07:29Z"
  mac: ENC[AES256_GCM,data:4ButUjNXf822iHOcSwye3nTtZC1mOhUplURXHTJgCuXh0UpXLncZFpZ27TzfHQby/hBAgCud340m82iaLraFjriyC6QIhZQfqL3nEEzfY8jhOgntfuuTudM1FMRvYsDcH4b+u9axSsLVm5vas+6W0bhk0mNLnJ6PAxS5i26Cjzw=,iv:FZznD4d+4xLcnBId/YnGynEQnDgo675tu/ojDJABbHM=,tag:56uMooLtKkwfTvyjoeY5Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
