---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncthing
spec:
  interval: 1h
  path: ./kubernetes/apps/collaboration/syncthing/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: collaboration
  wait: false
  timeout: 15m
