---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefox-sync-pg
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 8Gi
    storageClass: longhorn-r3

  bootstrap:
    initdb:
      database: firefox-sync
      owner: firefox-sync
      secret:
        name: firefox-sync-pg-app
      encoding: UTF8

  superuserSecret:
    name: firefox-sync-pg-superuser

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 384Mi

  monitoring:
    enablePodMonitor: false
