apiVersion: v1
kind: Secret
metadata:
  name: firefox-sync-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:L22OcqbFnf0=,iv:Fcz+IfzpuFI5fNB5tjvfD+LZUFowcf76c+bUfwu2ZQM=,tag:VaaYgPpoD83B2D5ue+ZPWA==,type:str]
  password: ENC[AES256_GCM,data:zVWX1Jix4EhH6boUGAEzj34FU3SpKtR6bzWpFzk3fzw3hecyi3yGHgzS8EPOoXJsQhE6SFrjRogjsSBwNJ/Jcg==,iv:9B62AYf63g5SAU6Hh2bWPUWL1SrauqJ4ohrYPlvOTR4=,tag:8cYIKVdrukloNQKazVvPUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIKzVjQkFsMmpoOThrNDRD
        a3BLbUVwaiticzlQayszWlpQN1FncFJqbkRVClpKK0ZCd1BqUHFzaEdkS2k2VXh5
        cWxnWFRscDFJSkgzSmVVVFptcmpOQ3cKLS0tIE9qQUdiWnFveU9uNmhVVnhDMFZQ
        NFFINWY1Q1RlMHpwSk80dzFFcndBWFUKqprgcQ3rpHlijnRRq2/gTBzULkwC3dgS
        Y4RgeGEGKjWjxF4Bm4Up13aXB+yIUH572BgaIwqp4+dBx3UQRvb2CA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T18:22:25Z"
  mac: ENC[AES256_GCM,data:LxyfqGV/tMp3CRsGw5k1NVNvMylgiBtDbv07adh0ihKOLZxSI5GsRvtzUKu/0cbirm8tyAXwnRHzcOQXC5dyzPm4txCkzzR1y9c6FrgqnaL4m4zM8S4lva8MNlsw8O11HhPEPGAzB2BrnCEYFAYtzzJQYisHsPKOQ9gqbxObTWU=,iv:aLdZ3MwUGN35PViYZq4Dun7WWXd1ROMEFyDigSrLN3k=,tag:sQ9p32boay84twRQ9O0/WA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
