apiVersion: v1
kind: Secret
metadata:
  name: firefox-sync
type: Opaque
stringData:
  master-secret: ENC[AES256_GCM,data:Qiftc6odjOem525GjG+9qhxagUQHIjV9kC5Y1hmGa38XjSdI5X7D9Txjm8TSj3w3gevNdKjYXx7We5+ODB8H3w==,iv:IDm2exqq7RzbdWqLo5wRtrMah96Xol3GCMflkZF3Zg8=,tag:P0mQ3KuUrQdaNh1Xe857mQ==,type:str]
  metrics-hash-secret: ENC[AES256_GCM,data:t2bbmBR3FGMi+WQm7SbhnnsKFy5EQ8mmuZqiTUWxovO68tVeXFHAZPljmQwDW0R2eMEVqHfeM234WSaKLbWHjA==,iv:bhEfHWgU4im6q6gvvouFbY2BiPfaC3NTzLGuj1PubhE=,tag:yg5s//W2y0w8AaHVkg01SQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ekJ3WHhXZGdibTFZRGpl
        aGRyUVNDWG53WThCd2NDSUE2MFlNdElkc0NzCkd1MDNsQzJYVTRxYkJIWmVaQklu
        azBSb05keGdJS0ZlaWtRT2o4N2xkYnMKLS0tIEpzZzBxRlNHR0VaNlpIV1NHcVJq
        Vldob2kwVDZMdlkxa3phVFEzN2VHVTgKgyRykWySWz5gt9K9xzOYMiXpF08bA01D
        Bubj9AE4BndvFfNRdrUsXSP1OSb7ZJx3wceWt/b9BVKGPePGItMSuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T18:22:25Z"
  mac: ENC[AES256_GCM,data:AoMIAt+tSOIOaxEOiEfK5q46PSGh4BJ0HOWgLAI5ojuYD9kSGiPRQh0F8S3Jh/UaRoS93Wc+F3Se0ZBXm+xcYNOa3o2tJ/sdV4bbBjMwmwhQv6HF2dBt08h3xynkAq0jyPfCG0sXnes2zT6kmzPjeBjGeD8jLrRH0w4CrzfUtoY=,iv:7N3p3eqWmluxayRETCPpwqhkmGi2FNHDu1b+cWw2g7Y=,tag:7RHaO0UnLf1r1lxV5Q2NIw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
