---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openstatus-config
data:
  AUTH_TRUST_HOST: "true"
  DATABASE_URL: http://openstatus-libsql:8080
  DB_URL: http://openstatus-libsql:8080
  FLY_REGION: self-hosted
  GIN_MODE: release
  GCP_CLIENT_EMAIL: unused@self-hosted.local
  GCP_LOCATION: self-hosted
  GCP_PRIVATE_KEY: unused-self-hosted-key
  GCP_PROJECT_ID: self-hosted
  HOSTNAME: 0.0.0.0
  NEXT_PUBLIC_URL: https://openstatus.${SECRET_DOMAIN}
  NODE_ENV: production
  OPENSTATUS_INGEST_URL: http://openstatus-server:3000
  PROJECT_ID_VERCEL: ""
  RESEND_API_KEY: unused-self-host-oauth
  SELF_HOST: "true"
  STRIPE_SECRET_KEY: ""
  TEAM_ID_VERCEL: ""
  TINYBIRD_URL: http://openstatus-tinybird:7181
  TURBO_ENV_MODE: loose
  UNKEY_API_ID: ""
  UNKEY_TOKEN: ""
  UPSTASH_REDIS_REST_TOKEN: placeholder
  UPSTASH_REDIS_REST_URL: http://localhost:6379
  VERCEL_AUTH_BEARER_TOKEN: ""
