---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: openstatus
spec:
  endpoints:
    - dnsName: "openstatus.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["external.${SECRET_DOMAIN}"]
