---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./configmap.yaml
  - ./storage.yaml
  - ./libsql.yaml
  - ./tinybird.yaml
  - ./workflows.yaml
  - ./server.yaml
  - ./checker.yaml
  - ./dashboard.yaml
  - ./status-page.yaml
  - ./private-location.yaml
  - ./httproute-dashboard.yaml
  - ./httproute-status-page.yaml
  - ./dnsendpoint.yaml
