apiVersion: v1
kind: Secret
metadata:
  name: openstatus-secret
type: Opaque
stringData:
  AUTH_GITHUB_ID: ENC[AES256_GCM,data:gbcTwb4uI34nFZfvNnsm6gIuhts=,iv:RTtsa/UY/Ijk3v6o14wICk4hlq/Uw38BWLOZ17t+Nes=,tag:1RIVB3mQIWpHVSo0PKwY6A==,type:str]
  AUTH_GITHUB_SECRET: ENC[AES256_GCM,data:TaBzqSmdGPcsuJgqjJBZstItkQEM2pM1j5nt1EamtKBdqeGBaIHO2Q==,iv:+jh/9uHoQ4BUT5vURWHXQtzfpPBhZKkL2jTPYC0B9Js=,tag:6mQmqi3cbulGpvWlW+9X4Q==,type:str]
  AUTH_SECRET: ENC[AES256_GCM,data:Y/uQrgTbGIqsgPuK43JphOKRYluVYFjH/npz4KcykRob/M5A02J4aq0VFbo=,iv:z0fn+74zGZd1u4i1o+iY/XjpH75BGPYuEwAAy+N2P8I=,tag:bozjAL/b/HrakPia4AxAFQ==,type:str]
  CRON_SECRET: ENC[AES256_GCM,data:VwdHyIM54jpcSvLv/HxjiisQwP/cPP9eb9oTl0G2q1zNvIxfnNS0043izYtmPj1SwQ/Vucx9C1CT+/efT8mNB37k,iv:rmxyoLJtgQC4lk3rSHzXDmZlRANM0MnM866nKdNajZk=,tag:6diUwsmF/pZ4tVEu1j3i3A==,type:str]
  DATABASE_AUTH_TOKEN: ""
  OPENSTATUS_KEY: ENC[AES256_GCM,data:17Wf/CA0x1XNPwXR77aD6CaB/tfsLfDxCJf72vRIeNNeHJt9S5KfjGURVDsdvUp5NjPGOnY=,iv:9ZwX4fJoLV7A/phjfuX4Q4pTBja05Qmxxk0LyivV2SI=,tag:vsQqOFP/MwMFpVNhKfBSLg==,type:str]
  SUPER_ADMIN_TOKEN: ENC[AES256_GCM,data:w+rrAZgZuo3ttd8B6qTY/60WzhiM4KtxCsAC5cFgzMQaub27j0Z3cPqIE5zjwemn,iv:A46j3Zqq7nySp2SzjdLbBnqdysiShpG33jRQ1Y3hyDo=,tag:GvzN3+pyB/Y76DFxwExc7Q==,type:str]
  TINY_BIRD_API_KEY: ENC[AES256_GCM,data:kdqJD0fgHQlHM1uPy4FFrZst28zlwOelSpIXfBwv1pIr1qHkytPRwl5BWz2W6I1s,iv:5XGk+OTwWSz1uyORfBfeBeXHBSXTtV3H7rGpk5pjvk0=,tag:wT46KQGo1A8Xuu5TBWiNRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNXY1SkJGajlzT08yckZK
        T3lkWFBSVlVFaXl2cklDNGVlWERVQXJXM0g0CjBRM2RVd0RoQmR5YzhmaGRLb21Y
        TjcvSjZaVjVSSHZ4ME5XZGl1ZGdaOUUKLS0tIGgyVzg4akFhRnM3VG1pd09tZW9W
        Vi9RNUgxL0tyQW4zY21NWEp6TTFVYmsK4Y+x/GhW3SxuHeEE79DQLEY2sK8guvo8
        93ZWTALZ4UAVW+ec0IAwRAZjcd+TWPGT/tw/2p7d8mCKz7tx0OGpmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-14T16:17:41Z"
  mac: ENC[AES256_GCM,data:9Qpj4MFqXWGCX6L86GxSZjF20iH7aP2YWDHP+xlMqj8HDd2zvxaVahK/4z7suDYtfX6Z98P/cuvCvsv/Kdic/nQZEPjbakZuka575nHiNXG76k16ycKGdEsOFh2HPpehQRo+jyxTejCB625nq46ioItcm5UljiwUymf69AI7wKs=,iv:4/vTzDWYKGaFhQyVufsNGRMlvDsZfZisrDZ10cLYqfE=,tag:IGfgoavvMN4zsxKP7kmmuQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
