apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:b95UMzYT5BfkGUb46i+KNzfMou/i8iBRzn+gLoOwTWD/96CCyboY83jZHvhLNCvX5JcBXldKJ+wQrqaF9CffVI8Ds/cvecaBgBXGsbVDIVHYWJNrtPy0kg4yX0X9Dgv97CYTz+zRGaXmk7x8+hjGE3vLyJG0KFTnSL6PH6CC/OeI/SFGYEXdERkLk3HH6TulJThKH+l6+Z3tPJgo4s3mHSH4K1mxuZQcw83uGzyAMbqpGFX9,iv:dqVS6K8LloQiFbRt34ofUOhl/qtwJJEJJ+5YXPfinLQ=,tag:faQMg+nqmITwCNkz62xIDA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNnRBSFkvVnlVU2htbndo
        ZUpzOEJaU2RUUEdIS0pXK3NIV3I2VUNNd2pNCkNxUCt3SVFnUUFqR3R1TXgwSlps
        Mkx6N241VDhNSFFUYnBJRnVIaGx4V0EKLS0tIGQrM1BQc1VNOHl0OWsxRHdBby9Q
        MDJGNStHNE5mZmpUMlIwYXFjS1hTek0K2eMkI34yyjJZU2A0cYSOrSdbBpyu9Jv8
        rXc18HjSJ1Q1+tof7KNCxNs27wxi1h0IPNrQYx1QkzfA4t+Aj3gv1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:17:55Z"
  mac: ENC[AES256_GCM,data:/SjYlgDI0ST3vQkmLLrJ4fGArc0jpLRrYmdtMcEwuNWDkp6poXKzA/QEu7v3nvMNet4aYdsGMvJJxbwyy0x0g5E4HyAp7tluvoKXL4ciiXT9ZhwqHLjCE8WkfXPQ/Hrw50JxL8Rfytghz1Bj81vr87O/kNksrk/eDVdik6Es6iA=,iv:I9nGMmFCziRKj7m9VzDelOEQp7WZdko/SLRmgaC0GB8=,tag:g5ugclskyO9c2/o/2H78TA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
