apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:M0hVhgqCbDkvfiF0EN3ahPtqHZQ/zq3FSlaYniH9QSQs9QRebnvLs2jck/4+3TyqEhS/K6e75Mpw5Byix3HSpVWxW/TD130izNfU/BjwpFeua9ZDqYYmNghg2v0wh0XlOwzUKx5rW+zH/9iiwCgYFrJ3sXDfby05+bnPzlGsfLfb6epOx1H6zcD5IJYDwWAUeERM4du8ZQaYnSNC5j+IDtt39t6B63oZwOMpa9lZ5VOv4g2v,iv:GEzf3t469rpIz5OVcslccNK6wQDjb3ocuGnnICJ6PuU=,tag:XXEU9z5BaRdqViMFlZtkGA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OWxvQUdOODNDT0FwL21r
        Q2ZVdmFZdzZsS3pRU3UyOFM3bERBYnJFQzNBCnZhbXhPZU5heUdvUjNqRzk5MUw4
        amNST2xqTit3THhFdHlSYjgySmFRY1kKLS0tIHdpU2hsaWZDanhHMVUxaGlGKzdW
        b2NYSXRIRE9FTGVzRjdqcmZPN2d4WlkKm4EhZOV5qSrdEd8T1EfHvCOeioCDN7+Q
        G0DqNM+Vg9ALAVQqtrYqNg9oX9pcV0NlTKoWQyjNI7ZiRA6a0RZHbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:46:05Z"
  mac: ENC[AES256_GCM,data:nezNe1PDW25TkKyBxdBTlvFByDg/rbhHUzGOu4iRusjtLFimqXC2IEcVuAYGwmaq7pSiX4pY13DcItZ49bEnenhNCuNYtAFfuO1Ptdbp3H6LQuLabmWGkee4x3ebgIy0JPp8+y+WSxUNjRqw7dgAwd/llXDSwlJeadXlzfDrOr4=,iv:FPrDQXKquQCVV9yR39bB6EmnCUFIEZmuBag3AHGW95E=,tag:0II4ph9D1pzv2/+vl7l3sQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
