apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:woD+3p56jOTQoYRFWIg7SrNfiHsMUsTqrp0G3vV2509xMFA0nfanejztSrc6EYSxbB9BgNy45yN3jEXfCCMrV9b+BSZt60VNWrdTPo1kesZnwHzlYpnn2aUt9i8sWDpWWpACsK/CECOs5DBeUqiISscXYsWUeO0aVACoIMYVAisQk3NKZAMb+uaJzejmdOqiJ6Ba1uCIo4LmzqryKeywBVHIjuPWYf7lmtXp7GeObpQH1dp0,iv:QbamHIVWJXLFHuV7p5zNj4zFiTLVZ3dWe95dxpTaGms=,tag:h//pxXKQvuM5tkokvh/dXw==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NE9wUGdZT0NYeEdPdGlZ
        ZHh6WVZQd3pxMVNlckVPM1VJclp2M0dodlVzCklKNFYxREZkTmp2dDRTVkNJSUhm
        OTVHaytLaTZzbElTNjFMUnEzNXhjcVkKLS0tIDJBQUo0VmdsNlB2eGc1bjQ3M2Q1
        ZGdXV1FJOHR4Ti8wWXNZRjNjS2dIR2sKmWFamiuEK2OfESgoZvrvNZrZQiQ1r+UC
        NM5Etx5/dvr2M4fqoXzHFw7sZ3LVp4RZ5kQU7x3O7IjLFaJzySEzSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T06:56:29Z"
  mac: ENC[AES256_GCM,data:+fHxqsLa0leFvm7rm38ShA6Su4HOAgy1pExQ0I0OcZcLFog4nP6CPV1AQgFthkFLQkTwwgLV9eJKAeqbvLZM6rWg9lB3rkWfTbkQvW6Nm2QxhOTXoKlHcvZn1K0yCGuz1P1r8yzNH8yxPLgk4bX+HMYrTaxgBBqQ8AsOhKiCTec=,iv:2ulSBRqWMYb/P+8A3u/8YeCZAADQ1bvE0R1rZ2UQlfM=,tag:k9O2hchvr/K30M2Tef2Pog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
