---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: collaboration

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./firefox-sync/ks.yaml
  - ./matrix/ks.yaml
  - ./syncthing/ks.yaml
