apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Io7bqbbv3Q782oxh47qpP6Bhlj9fZH7mY/tjwq6hDNP9MzG8bd5yQA==,iv:UPNUXHfbOe+hQ9frdoZUG7RObHmXYvdmrqtZFO0GkxY=,tag:8O8uCqJVw6h+v+oXndOuNA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR3FMZGpaY0dLYXVGdXFy
        TGoxOXRxRmJ1ZzdETWs2bC9aVnBhdmxrcWkwCmxTM1hNeVJiMlAzRHhLTWVZMXg4
        TklOdDZZMlZtd2hEek1hVFVvZUJObmsKLS0tIElIUnNlbHg3RGg1WVNRRUQ4dWtU
        eE9HNm5rZ1ZqVFlXblJvdWdOQ0RQTXMKd2ds4J8BpApyUq7mYGH5cQ0nOiabbQkE
        vzygziZ1zSbOv1KmBz8xiTR5j5dgJz7gT+2OjJ4wygGdjYCMNc2GNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T13:31:43Z"
  mac: ENC[AES256_GCM,data:+McActBkmepMGnVvZuXGWDDdMb6sCoTRDtl4vvY1MjnB6ysJFeamC1gOJJoWOdlQRy20vXsh4f1gIamXpmoeLWVoILkD+84PihY+C2DBO285zenlCXnAbmFNZFJHqJC94O/+MqUuxvP2aOQb58tU0S8EFuTd8ClbXTDwoO0jhOA=,iv:2jEat8P+6PrBR4w7WHyVMTrpu6qaaz/8rIx3u0Vp/w0=,tag:vHY+EpCV4Tu+ZXJKU179ig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
