apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:FYFrbEbXPIyQcHpTylKbOkyATRxFu1hqr4UQ5kGGixXbwH2IkDIEIw==,iv:luGmvnJGcQbKcmUEBhg9djpjRs1IN2Tyhzn6GAAKsoQ=,tag:zqSpK3LeBvUPYyZwbCDVbQ==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTDl3OEF3SlpKU2dBN3E5
        TDBKa0ZJcG16eTh0U3dsaFpIRkZNeXNibjFzClRhbkNlYUhIeEI5T0M1NnB2SXQ1
        eXpxWlNmR01ONEF0ckRpYjdyc29hRlkKLS0tIDloMkxURGh3Yi95aGJwWWNCcmpY
        cTNVMDA4YmZTdGVmODh4YW81RmFYMjAK+h3mghrkDVmTkaB2q4b5ddLVM1OcKB+y
        nyJRkDR+hjTqvcprZ+Id34QluaF7zeYlVsOMEiLOJbj+zbcKNWFT+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T05:34:04Z"
  mac: ENC[AES256_GCM,data:iOy3rmJCMcGZ8YXmwKj2BxvGWKu4FtoygheFRSEoUoPBY0mnxL5H9tg7bse/dvb+wDBDvSOPV4oam9hy7ZoEfb72Nf5GV+CiKe+jiiLCSCjVUC0sekNvhiBmLhkld1t0121ns5UmvY4nNn9Qr61ON8ufvxIIUCpz9Hq5L574lCM=,iv:3VZh0WHeX/WXj4xdZH/fOwFy5LpAFDMOH7gu575BTm4=,tag:bB5FSla4wDpnPfevoVpKdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
