apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:L8jJ0rYbcBAMpvvlU7bwKPWajYjgKtpxMC2HXNfo4UnrUAh2tnfjow==,iv:zRkDD52UEntLiy+0c2wtbjy85i/5rcpZvjBgVZz63m0=,tag:ARlRvdgVzyjF4k0eE9OtaA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdjJVVFkxd005U3plMndN
        VU5VUTQyL2dLTTZJdUVmT3BvZlhwTHlWbXpZCklPdkw5aENUNWtzbUM1d3NpcG9n
        YWdvcm03SzBYZkpoeGFiUURITThoN0kKLS0tIEFNUGFVZm55amF0SDFYK0FSWFlG
        SnlSeFhxMjhhdkNBSFoxNEM2UWlndVkKIWqAjg22IBOhIUd89yQFUzw6ImtbDnZH
        9JyBZ8PxQFi2nTg/TQ74d2TlpqV69ObrijnWuR71YXXAhEmWY/u0dQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T05:08:06Z"
  mac: ENC[AES256_GCM,data:ojQ+ao7usOgBrHulKoo0F9eJEfFIKB0YhuBdaSVHsydgFJ8ZigyhpuD6CYp4gPoAaFPUs9uDHECzE5YEv9IvcjPtCRsBITT0LNW8RmZVdXItciHRPuJhrjqTemjEKFhKQhnNX1Bvh5B+yIjlowZ2kERvGQrk0g9v2xAC2chFx3s=,iv:g5BTdqeSBGms5j980bIDGuA6wOl9OyrlX62MCHscmbA=,tag:JLH1Zy+ArkAtKD6Kvk1Ssw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
