---
apiVersion: v1
kind: Service
metadata:
  name: envoy-internal-tailscale
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "internal-ingress"
    tailscale.com/proxy-class: "proxied"
    tailscale.com/tags: "tag:talos-ii-operator"
spec:
  selector:
    gateway.networking.k8s.io/gateway-name: envoy-internal
  ports:
    - name: https
      port: 443
      targetPort: 10443
      protocol: TCP
