---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: searxng
spec:
  interval: 1h
  url: oci://zot.registry.svc.cluster.local:5000/charts/app-template
  ref:
    tag: 4.6.2
  insecure: true
