apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:WMHsRyFLknVAWFD4B94pCq4SWHfTFXRqFtyN+mHaEsugLFCz6IfwPtpgNFbbgwkn/+B7Fy95Tmqm37qm287KaA==,iv:9UMbxxmFdxwAQnIaRlvEJuR8Th61/K/OIT1Ht2ve3/k=,tag:wQxW7rYHyQYP8X2hq+8YUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0dTT2dhRGxzK2NsODlv
        YVB4c1N2WUN1Q05JaUJoZ0MxWEF0eWErK1hBCnEyZzV6V3JWODRVMjQrMENidDJL
        eDd6eTVkSi9GN2FkM1dmZXN6SFRFclUKLS0tIG1kZWp0RFNVRGxVMk45WkJ0dm40
        dVhuYnREY2luYjZ2QUJpY1RGbU9XRGsKUWX8t4O8XK8jba2VooT205sUUk0oedU8
        yFKLa6PSnBHSMRNyzNHSCKhlDeI0iTeuFI1Eaf1cn7IzKcwMEIfGUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T04:53:58Z"
  mac: ENC[AES256_GCM,data:i6biG7sevksLv6X3fW6derBnPoAQqAM0P2jt/oEEtx+81c8mhzgYXdRMk4ZkO2+RSwMSSmohkpAULshGKod61fpETpmfHHhD6PjfNS6w083uC22w45bl16eLqAmM7qhNNqoY8IAVx3EM4PjukF9cV31fZH2Mt+mvwmKClWPjj5o=,iv:BrwXxCoPKU8mHB6wCNCsgak4d/Z7IAw2fOAflz50t3Q=,tag:Eydb21u4LjVa2Fi+uizIyw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
