apiVersion: v1
kind: Secret
metadata:
  name: matrix-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:qSbK9Ir6Qb4=,iv:IQyGvpP7+LdyHJuWuT5t/U9ozeGuczfOqDrYJeGM17M=,tag:tXgJjnomJ+ZnI5OnmVQ/KA==,type:str]
  password: ENC[AES256_GCM,data:9PcAJgBsb8chZqoUDZKWFqZqpnKFzm4RpQa5w9Y1IkDZT5DDrtnIBRWlag==,iv:bxdhn6UgySCK5NVou6I55miSpWXLMRsdKuvhZiY/OWU=,tag:GQ78fm+G9QcMVZOs+YCy9Q==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOCtWNkJUTDA3RGNYekV5
        akVwWG0zMlJtMWxjR0U1aUZzWEpZbXFhc21rCk82aTFpQTBGSmtsRzZad1hURGpt
        d05uS291bHVjOE0weVp4RDFFMGFGK2sKLS0tIGorNlBzdnRGblBNUGlnMW1XWVBk
        QTIwUkNRYmFpZUNQUGtNa0RmbWpkTXcKSJD+9960b6rk42KAsONCv+b3Be2WFKnZ
        AwRszDFN/GkoE3KGf5dU1R1aqE9HCFtgGgN23kvDhfqzTJyjy88i8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T12:41:44Z"
  mac: ENC[AES256_GCM,data:4rFGwxI825sfvXpViCjkrzJyooxjdzMG/3gKV8IakrEJmjWIhxkEj8vbqqhJoL+9eSOTj9eiOIP4op/2m79dbyoDqqIyfmClkjTnbHMvusFQ/WXZOQInEZrHgo4AYK5uniKd7W+QgVFeQKGPc/pkZqRhQ9JWYNpEFnAr8Mh9u4E=,iv:YrEXHQ6IrkSu6ANe7qp9I/pai1aLRh/cO6W3O7rR9CY=,tag:nnPuZiOI5VN3sdy/9fEDPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: matrix-pg-app
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:vPpf+EnzLA==,iv:jObECF59O7lVji520w24DZA+nc4CHvjs/lzQi55p20o=,tag:SkBcFU2lm4LHyteZKmGLfQ==,type:str]
  password: ENC[AES256_GCM,data:K3bbGQjg0vkJAaYRjWksQONRxjCArZzPSlZRkAsk7T49qkE7Xyj2knFOAQ==,iv:PQ9MFDgs/ybsLjlbxMht4U+X+hqNjpM3DwZBaVAGH30=,tag:5rrJyCbdej1CG1VW+jUtWw==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOCtWNkJUTDA3RGNYekV5
        akVwWG0zMlJtMWxjR0U1aUZzWEpZbXFhc21rCk82aTFpQTBGSmtsRzZad1hURGpt
        d05uS291bHVjOE0weVp4RDFFMGFGK2sKLS0tIGorNlBzdnRGblBNUGlnMW1XWVBk
        QTIwUkNRYmFpZUNQUGtNa0RmbWpkTXcKSJD+9960b6rk42KAsONCv+b3Be2WFKnZ
        AwRszDFN/GkoE3KGf5dU1R1aqE9HCFtgGgN23kvDhfqzTJyjy88i8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T12:41:44Z"
  mac: ENC[AES256_GCM,data:4rFGwxI825sfvXpViCjkrzJyooxjdzMG/3gKV8IakrEJmjWIhxkEj8vbqqhJoL+9eSOTj9eiOIP4op/2m79dbyoDqqIyfmClkjTnbHMvusFQ/WXZOQInEZrHgo4AYK5uniKd7W+QgVFeQKGPc/pkZqRhQ9JWYNpEFnAr8Mh9u4E=,iv:YrEXHQ6IrkSu6ANe7qp9I/pai1aLRh/cO6W3O7rR9CY=,tag:nnPuZiOI5VN3sdy/9fEDPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
