---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: multica
spec:
  interval: 1h
  url: oci://zot.registry.svc.cluster.local:5000/charts/multica
  ref:
    tag: 0.4.24
  insecure: true
