apiVersion: v1
kind: Secret
metadata:
  name: multica-pg-superuser
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:NE2BCpMgqo0=,iv:Br33tO3z3xMVA1hIpitZBOOEnVxNvVUBinQXVOVejcE=,tag:/qCfcJHTo2bMtUvkZ6Dh5w==,type:str]
  password: ENC[AES256_GCM,data:LYvXgF+XfHkQDHCfHIo6KnbxXFwIQWz5PsgoSq03LIw38j12cHN5VDcSgBlZ+wDI2Hq1oQBlp5lhBxDg92b1uw==,iv:SgIj3xrmM3YySPvn5/JEAA06uQXjnuvxZ0GVJH4xTZc=,tag:fMCtJES8arMTULVh+De56w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUG1jb3VPekVsUUtHYkkx
        MjVGVlpXeHJuTEErajMzdVhWU011ZXVEcWpBCjlMYmFZbm1NUTZHcHJ6Y25sKzlB
        Z0hGVDFucUwvTkMwejNOQlhTZi9LeW8KLS0tIHZ0SGl0SWhIRHVlUHVkZ1NEMTZa
        SlR2bHJJa2huekJEYmhVMFc1TUJVQ2sK8T3MedbG8A5/fvMYwAvSDgxFu3HYpCkn
        UNgZ5Jd2DwaR9qtlRtrVEBVzZV7HvmnuBuQ54Z50rf6oYEH/aW9YKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T07:57:08Z"
  mac: ENC[AES256_GCM,data:Ija/a8BNoKhiAe+yCi03KmkdWNdsAU4n/98A6wpO7oszfAkJY1i396FqwgzwZrwHGT9HMpD76i+3DkRJR7g+T1jDc63ui3u2YNTFnhsflLFGi6reqzW047q3grQ8zYE1rFVM1TDVlMUY3+AiWNDPvKtk+NfuidnpK4oJ65DdSsw=,iv:ryN8IB1S6blht4O4d9IE9sXz49Xlqs8Mk9FvZrOi+ls=,tag:Sqndmee9FA6FJqEHQC9y2Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: multica-pg-app
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:y1MGhh4t1Q==,iv:nU8XSvQlUJ00TnjgX0arQDcLWH7vzdrDft8kev+IWxw=,tag:eMl5Cfl5snZvAZUPix1Tqg==,type:str]
  password: ENC[AES256_GCM,data:ZIIv/Wu4fEf6i2BAhwa3I0MmzP+YXs+93c7V11yp2eHbf54idNrfEIDFv3frmy9KSzv0kz1AENqCRWSn/q4xFA==,iv:Ia1Q5e5rVSGk89ypavQlzmAXebH3w1a/3bPYcUNQD5A=,tag:VKTD8n9vNinIqRSrTTTW8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUG1jb3VPekVsUUtHYkkx
        MjVGVlpXeHJuTEErajMzdVhWU011ZXVEcWpBCjlMYmFZbm1NUTZHcHJ6Y25sKzlB
        Z0hGVDFucUwvTkMwejNOQlhTZi9LeW8KLS0tIHZ0SGl0SWhIRHVlUHVkZ1NEMTZa
        SlR2bHJJa2huekJEYmhVMFc1TUJVQ2sK8T3MedbG8A5/fvMYwAvSDgxFu3HYpCkn
        UNgZ5Jd2DwaR9qtlRtrVEBVzZV7HvmnuBuQ54Z50rf6oYEH/aW9YKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T07:57:08Z"
  mac: ENC[AES256_GCM,data:Ija/a8BNoKhiAe+yCi03KmkdWNdsAU4n/98A6wpO7oszfAkJY1i396FqwgzwZrwHGT9HMpD76i+3DkRJR7g+T1jDc63ui3u2YNTFnhsflLFGi6reqzW047q3grQ8zYE1rFVM1TDVlMUY3+AiWNDPvKtk+NfuidnpK4oJ65DdSsw=,iv:ryN8IB1S6blht4O4d9IE9sXz49Xlqs8Mk9FvZrOi+ls=,tag:Sqndmee9FA6FJqEHQC9y2Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
