apiVersion: v1
kind: Secret
metadata:
  name: multica-secrets
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:Bit33AbVDGEcQCEZknDKCSwAFG0FwDjGbp4x0KBQtSegrEDp8TEgptsZ1KCBB0eME9rD8tzG4lXqd0n+id0x8A==,iv:/lM+S887NbINFgnaTCZF7r9XEON+qjNDqRr+J0JN9Pk=,tag:FfyAUe5BIZ3LUzvZnTUsYA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:JVWrbUcF4Gjn+nmj4nm3VapKoiRuDbeVRhqpkyOxItbrjXQ3Y1QvXoxQgs75C2cog7HWG+HyLo2EboqrrOyGsOwuMF5BcEdwCfXkkVK7VKgLwe/y07EAn0SI6MFq8EqmvCq9NX1TEurD0kAxoGuyeSFCuyexzPJXg4ELGfqYDsaxK9ohwQpy3bY9fmt0fRz66ma2aXuchrolQ3lJ,iv:FtVLUlGCtId+roez7V18S+HDlxjfygef0wKaoEHT1Io=,tag:LfJH77WTGSTvLFamztD1fA==,type:str]
  AUTH_TOKEN_TTL: ENC[AES256_GCM,data:IUOvqGk=,iv:faapEQgSEYbSTPKXe1is1q6/3AQwTnYWGYLQaziarXE=,tag:A7BFxAq5CNgdqC119DTEMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycXVVSDU2bXY1YUFIZExR
        QU9lYTNsMDQ1clBXNjRhaUJ2SmFhNTBOYzF3Ck5NUTRRYnRkMDlTMWZPaG5XbVVl
        MjA3ZDBQdU9Da0F0YkwzbHJWUi9ZVkUKLS0tIGJaZEtuTUQzcElvMWhjcDFYdmN6
        OVVFaFlEbWhpd1BJbXNuTU9XR1JZb1UKSihZeEqh2b01RSet6trijSbZu4g0E/rL
        xV2M7qin9W1ZS0mF3Cddx0y1YYtH5r4VO6uQgOZDIvcgQSPXXaiLGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T13:28:16Z"
  mac: ENC[AES256_GCM,data:yTnJ9l9nm6jZxHR+rwBcsOtqbdr+EYp3LIbomahtvisG08GYdtLSLFbo58pn5jCYqJbpwrDaqfXgY7XgLpBXu+st2wx2OOrmvdG6zbjjw5eBUONIzaoT5whBRVg9NDoxZnZ7e+LYnieUfw/8JoGcKRFg+CNVP/66uJstK/GQP1Q=,iv:lpzUVvGw19iw84FU2iDz0YUHytTzSbZOgHjgXZuussE=,tag:efr1gOmli29LQmS2uo8jvw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
