apiVersion: v1
kind: Secret
metadata:
  name: multica-secrets
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:Bit33AbVDGEcQCEZknDKCSwAFG0FwDjGbp4x0KBQtSegrEDp8TEgptsZ1KCBB0eME9rD8tzG4lXqd0n+id0x8A==,iv:/lM+S887NbINFgnaTCZF7r9XEON+qjNDqRr+J0JN9Pk=,tag:FfyAUe5BIZ3LUzvZnTUsYA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:JVWrbUcF4Gjn+nmj4nm3VapKoiRuDbeVRhqpkyOxItbrjXQ3Y1QvXoxQgs75C2cog7HWG+HyLo2EboqrrOyGsOwuMF5BcEdwCfXkkVK7VKgLwe/y07EAn0SI6MFq8EqmvCq9NX1TEurD0kAxoGuyeSFCuyexzPJXg4ELGfqYDsaxK9ohwQpy3bY9fmt0fRz66ma2aXuchrolQ3lJ,iv:FtVLUlGCtId+roez7V18S+HDlxjfygef0wKaoEHT1Io=,tag:LfJH77WTGSTvLFamztD1fA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycXVVSDU2bXY1YUFIZExR
        QU9lYTNsMDQ1clBXNjRhaUJ2SmFhNTBOYzF3Ck5NUTRRYnRkMDlTMWZPaG5XbVVl
        MjA3ZDBQdU9Da0F0YkwzbHJWUi9ZVkUKLS0tIGJaZEtuTUQzcElvMWhjcDFYdmN6
        OVVFaFlEbWhpd1BJbXNuTU9XR1JZb1UKSihZeEqh2b01RSet6trijSbZu4g0E/rL
        xV2M7qin9W1ZS0mF3Cddx0y1YYtH5r4VO6uQgOZDIvcgQSPXXaiLGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T07:57:08Z"
  mac: ENC[AES256_GCM,data:V4RoaR2KW1x3O/881AIyv+rdkkpjViClLwd3Xc667o77eh/hrJrbA0W1y1fmBfwjbXXiCXMx5lmYSLhodwrlJxlnPgQ1oWf2w3SkJsJY/upESZAkIa4voh3VjBgHSS4sXujP0V67w94on4tRacu97r/V8+pHEf5tnR4zIPnAK3Y=,iv:ovj7tOShdtdverDLwf4FsTqgaJ9WNCipfTEraX022Zs=,tag:XdqRJI37JQULlsfEwyq1ag==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
