---
# Pre-pushed from `https://guerzon.github.io/vaultwarden/`:
#   helm pull vaultwarden/vaultwarden --version 0.35.1
#   helm push vaultwarden-0.35.1.tgz oci://172.16.80.240:5000/charts --plain-http
# Same pattern as authentik / tailscale-operator — keep flux's
# source-controller off the public internet.
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vaultwarden
spec:
  interval: 1h
  url: oci://172.16.80.240:5000/charts/vaultwarden
  ref:
    tag: 0.35.1
  insecure: true
