# Carried over from swarm-01 verbatim. SSO_CLIENT_ID matches an
# existing row in authentik's restored DB (`Vault @ Beacoworks`,
# slug=vaultwarden); rotating it would require also rotating the
# row in authentik. ADMIN_TOKEN gates the /admin panel — keep
# secret.
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:KJIt4sN+MlvBbXbZVHc/7tLsbBzejaIYstgQa4MgQQEbmBBqqpA9H8JGxOcMktu9zhqjo7YzV3stTIS1UsVVtg==,iv:DRjSypyQztGJPyzVCUHP2C3xubMF/fMqbJV5LmdLdQM=,tag:2o1dwTUBD04BbfgvSasaoQ==,type:str]
  SSO_CLIENT_ID: ENC[AES256_GCM,data:yFYksYF8GKIQcJhqM7SI9Og3g2ykIyvBgWpcTrlhtIx7JzaS06qIPQ==,iv:05boe7/k7bp8fZbBquOm2VQ3BCkpgcb76GVWiXQ0tb4=,tag:HRaOT7Pp9uPyhfod85j1sw==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:f/+9VthVu8cVuWNHSsqTved8kSQjXYBUyeLArJfe0zcwVzaAILMLPP79O8JnLS0PSKMA+SDRz2RfKxABjTqNN6/Fso5HmkKaWCe9tPN8Kvuj0GaN24Ofzy3avQ+LNxQQWiB3b0XrOAJOlM5aZUseri4EbW65gMS5xBp2hokx+oM=,iv:/3lbgSjYTQUhfZAgm1EqGnPlC3Q6HeCNU8VnQBH2X9g=,tag:aCLCyFI8EjLXFA7L2iXUxA==,type:str]
sops:
  age:
    - recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTnFuZUR4SE00ejVwYzkr
        QVRJRWxaYkZldUNyQktjYk5Ub0d0aU9VSnhnCjhUc0J1cFkxNzE5TDAvUHdoMnU4
        ZisxUEFmdEQ3NVdaVk5sS21lOUQxQ1UKLS0tIDJZUllYVUtVRUxzZWRiUEZNNWQ1
        a3dLVzlrYTZOaGJyL1NTdUNYc0JaaFEKrST6D3q2ktC1XG1glpgm/mU79KZcC4Jg
        HH4tGEzQXoZrAZMNT2CefyYCyf8nxQGPbpEGHTkrYLru4Mt5aYN+9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T12:14:14Z"
  mac: ENC[AES256_GCM,data:DbxfxMlo16loC8WnngMJE3Bj3EOGnJUo0H+TicJn952V5l0FdKRxYXrh66JKtHVkbVJrHlhSPkoNxcnrAzFxYFS6yfAa3TfGnzcuuSqpGpI5g5vU5/oIApzXLKC1ZWS3nnm8DJkaGz9yhMcelexkHvIxn9JkL+8HQADGwn0h0MI=,iv:aLwbaIjf0Xwy+yd76TpHAiPmvzs0yVnuCMI/bHAgAjI=,tag:VVP6sHL5uMss1UxyH9+oOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
